In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error,r2_score

In [2]:
df = pd.read_csv(r"D:\Roshan raj Mahato\Desktop\Data Analytics\Data_Science_By_Santash_Sir\Datasets\student_performance.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB

In [3]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [4]:
df['Extracurricular Activities'] = df['Extracurricular Activities'].map({'No':0,'Yes':1})

In [5]:
X = df.drop('Performance Index',axis=1)
y = df['Performance Index']

In [6]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y,train_size=0.8,random_state=42)

In [21]:
xtrain

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
9254,5,49,0,7,5
1561,2,48,1,7,6
1670,2,81,0,7,2
6087,2,46,0,6,1
6669,8,47,0,9,0
...,...,...,...,...,...
5734,8,50,1,6,6
5191,4,68,0,9,3
5390,9,48,0,7,6
860,1,47,0,9,0
7270,2,46,0,6,6

In [22]:
ytrain

9254    36.0
1561    25.0
1670    59.0
6087    22.0
6669    40.0
        ...
5734    48.0
5191    51.0
5390    44.0
860     20.0
7270    24.0
Name: Performance Index, Length: 8000, dtype: float64

In [23]:
xtest

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
6252,5,69,0,8,2
4684,2,46,1,4,8
1731,7,56,1,7,5
4742,6,42,1,8,5
4521,7,53,0,4,6
...,...,...,...,...,...
6412,2,70,0,7,3
8285,4,79,0,9,3
7853,2,40,1,7,2
1095,3,83,0,7,5
6929,5,60,0,8,4

In [24]:
ytest

6252    51.0
4684    20.0
1731    46.0
4742    28.0
4521    41.0
        ...
6412    45.0
8285    66.0
7853    16.0
1095    65.0
6929    47.0
Name: Performance Index, Length: 2000, dtype: float64

In [7]:
model = LinearRegression()
model.fit(xtrain,ytrain)

LinearRegression()

In [ ]:
model.coef_
# [2.85248393, 1.0169882 , 0.60861668, 0.47694148, 0.19183144] for each fearture 
# slopes are the weights
# weights :- It tell the important of features

array([2.85248393, 1.0169882 , 0.60861668, 0.47694148, 0.19183144])

In [9]:
model.intercept_

#y = -33.92194621555611(base value of y), when all the features are zero

-33.921946215556424

In [10]:
#weights ?
#it tells the important of feature

In [ ]:
#model.score() == r2_score()
'''
#model.score() == r2_score()

model.score(x,y)
for test => model.score(xtest,ytest)
for train => model.score(xtrain,ytrain)
'''
test_score = model.score(xtest,ytest)
train_score = model.score(xtrain,ytrain)
print(f'Train Score : => {train_score}\nTest Score : => {test_score}')

Train Score : => 0.9886898790682355
Test Score : => 0.9889832909573145

`Conclusion : `

`Train Data` => Model captures 98% of the pattern from train data.

`Test Data` => Model captures 98% of the pattern from test data.

The performance from both train and test score is good.

Model learns the train data pattern properly instead of memorizing and 
the performance from unseen data is also good.so this model is good for future predictions

In [12]:
''' 
syntax:-
r2_score(actual_output(y),predicted_output(y_pred))
returns float

'''

' \nsyntax:-\nr2_score(actual_output(y),predicted_output(y_pred))\nreturns float\n\n'

In [13]:
y_pred_test = model.predict(xtest)
y_pred_train = model.predict(xtrain)

In [14]:
test_score=r2_score(ytest,y_pred_test) #ytest is a actual output for test data
train_score=r2_score(ytrain,y_pred_train)#ytrain is a actual output for train data

In [15]:
print(f'Train Score : => {train_score}\nTest Score : => {test_score}')

Train Score : => 0.9886898790682355
Test Score : => 0.9889832909573145

In [ ]:
mean_absolute_error(ytrain,y_pred_train)
#ytrain are Actual xtrain(input) Output , y_pred_train are predicted value for xtrain(input)

1.6193054830334268

In [ ]:
root_mean_squared_error(ytrain,y_pred_train)
#ytrain are Actual xtrain(input) Output , y_pred_train are predicted value for xtrain(input)

2.041993107119857

In [ ]:
mean_absolute_error(ytest,y_pred_test)
#ytest are Actual xtest(input) Output , y_pred_test are predicted value for xtest(input)

1.611121346312304

In [19]:
root_mean_squared_error(ytest,y_pred_test)

2.020551508505005

In [20]:
mean_squared_error(ytrain,y_pred_train)

4.169735849525008